@echo off
git rm --cached *.zip
git rm --cached *.log
git rm --cached *.o
git rm --cached *.choulei
git rm --cached *.Leige
git rm --cached *.uvoptx
git rm --cached *.uvprojx
git rm --cached *.dep
git rm --cached *.bak
git rm --cached *.Bak
git rm --cached *.scvd
git rm --cached *.txt
git rm --cached *.ini
git rm --cached *.crf
git rm --cached *.d
git rm --cached *.axf
git rm --cached *.html
git rm --cached *.hex
git rm --cached *.htm
git rm --cached *.lib
git rm --cached *.lnp
git rm --cached *.sct
git rm --cached *.__i
git rm --cached *.map
git rm --cached *.lst